-- PRIMEIRO cria a tabela stock
CREATE TABLE IF NOT EXISTS stock(
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    description VARCHAR(255) NOT NULL,
    location VARCHAR(255)
);

-- DEPOIS cria product
CREATE TABLE IF NOT EXISTS product(
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code INT NOT NULL,
    quantity INT,
    description VARCHAR(255),
    value NUMERIC,
    stockLocation INT,
    CONSTRAINT fk_stock
        FOREIGN KEY (stockLocation)
        REFERENCES stock(id)
);

INSERT INTO stock (description, location) VALUES('main inventory', 'london');

INSERT INTO product (code, quantity, description, value, stockLocation) VALUES(200,10,'HMBUGER',30,1);
INSERT INTO product (code, quantity, description, value, stockLocation) VALUES(1,10,'BATATA FRITA',30,1);
INSERT INTO product (code, quantity, description, value, stockLocation) VALUES(3,2,'MACAXEIRA',30,1);
INSERT INTO product (code, quantity, description, value, stockLocation) VALUES(100,5,'PREIA',30,1);
INSERT INTO product (code, quantity, description, value, stockLocation) VALUES(120,143,'QUEIJO',30,1);
INSERT INTO product (code, quantity, description, value, stockLocation) VALUES(130,30,'BACALHAU',30,1);
INSERT INTO product (code, quantity, description, value, stockLocation) VALUES(240,22,'SANDUICHE',30,1);
INSERT INTO product (code, quantity, description, value, stockLocation) VALUES(500,250,'QUEIJADA',30,1);