-- PRIMEIRO cria a tabela stock
CREATE TABLE IF NOT EXISTS stock(
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    description VARCHAR(255) NOT NULL,
    location VARCHAR(255)
);

-- DEPOIS cria product
CREATE TABLE IF NOT EXISTS product(
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code INT NOT NULL,
    quantity INT,
    description VARCHAR(255),
    value NUMERIC,
    stockLocation INT,
    CONSTRAINT fk_stock
        FOREIGN KEY (stockLocation)
        REFERENCES stock(id)
);